// Sectores empresariales comunes
export const COMPANY_SECTORS = [
    "Agricultura, Silvicultura, Pesca y Caza",
    "Minería, Canteras y Extracción de Petróleo y Gas",
    "Servicios Públicos (Electricidad, Gas, Agua)",
    "Construcción",
    "Manufactura (Industrias manufactureras)",
    "Comercio al por mayor (Mayoristas)",
    "Comercio al por menor (Minoristas)",
    "Transporte y Almacenamiento",
    "Información (Editorial, Cine, Telecomunicaciones)",
    "Finanzas y Seguros",
    "Bienes Raíces, Alquiler y Arrendamiento",
    "Servicios Profesionales, Científicos y Técnicos",
    "Gestión de Empresas y Organizaciones",
    "Administración y Servicios de Apoyo, Gestión de Residuos y Remediación",
    "Servicios Educativos",
    "Cuidado de la Salud y Asistencia Social",
    "Artes, Entretenimiento y Recreación",
    "Alojamiento y Servicios de Comida",
    "Otros Servicios (Excepto Administración Pública)",
    "Administración Pública",
  "Otro",
];
